### ISSUE TITLE
Articles [Blog List]

### ISSUE THREAD

**Issue by ranzey** [hackdawg-ph/hackdawg.com#10]
- [x] Should be 3 columns for the blog cards. [I'm using desktop version]
- [x] Replace Contributor to Archives

![image](https://user-images.githubusercontent.com/41352509/82443634-65ce8900-9ad4-11ea-9c94-108f9bae6079.png)

**Comment by jovertical** [comment]
Closing this after pushing: https://github.com/hackdawg-ph/hackdawg.com/commit/8d3b2a5a491b1527bf29672b7fc3882cd79312e4
